### PR TITLE
Bump Certbot and ACME dependencies with new tests added

### PR DESCRIPTION
**Pull request by tedski**
The outdated dependencies are blocking home-assistant/addons#3751.

This adds some testing to the Authenticator (more to come later).  The tests are configured to run via pytest and the GitHub Actions have been updated to run the tests during Compatibility Testing.

This also bumps the Cerbot/ACME dependencies to 2.11.0 to keep up with the current state and unblock home-assistant/addons#3751.

This drops support for Python 3.7 as it is EOL.

### CODE REVIEW

**Comment by tedski** [comment]
@stephenjust @dalbothek can you take a look at this and help unblock projects that depend on this library?  Thanks!

**Comment by heapoutofspace** [comment]
Thank you very much for your contribution! I might not find time to review your changes in detail until next Tuesday, but I will make sure to get a new version out by then.

**Comment by tedski** [comment]
Any chance this can get reviewed this week, @dalbothek ?

**Comment by heapoutofspace** [comment]
Thank you for the reminder, the changes have now been merged and a new version [0.7.0](https://pypi.org/project/certbot-dns-cloudns/0.7.0/) is available.

**Pull request merged**
